# Generated by Django 3.1.4 on 2021-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_auto_20210417_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(default=91, max_length=11),
        ),
    ]
