# Generated by Django 3.1.4 on 2021-05-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_auto_20210511_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='user', max_length=250),
        ),
    ]
