# Generated by Django 3.1.4 on 2021-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
