# Generated by Django 3.1.4 on 2021-05-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0027_auto_20210511_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
